# fly.toml app configuration file generated for wattson-api-ivory-seastar-408 on 2026-09-19T19:59:28-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wattson-api-ivory-seastar-408'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  WATTSON_ASK_MODEL = "gpt-4.1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
