#!/usr/bin/env python3
"""Generate PROVISIONAL fixtures for the Wattson web app.

Reshapes data the pipeline already exports (dashboard/public/data/regions.json,
heatmaps, alerts.json), the mock company file (claims/companies.mock.json) and
the hand-mapped operator table (scripts/operators_manual.json) into the shapes
the future API will return. Yash's fixtures/{region,site,company}.json (and then
the API) replace these. Stdlib only; run from anywhere.

    python3 fixtures/_generate_provisional.py
"""
import copy
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))   # web/fixtures.provisional -> repo root
PUB = os.path.join(REPO, "dashboard", "public")

GENERATED = "2026-09-19"
NOTE = (
    "PROVISIONAL fixture generated by fixtures/_generate_provisional.py from "
    "dashboard/public/data/regions.json (plus heatmaps and alerts.json), the mock "
    "company file claims/companies.mock.json and scripts/operators_manual.json. "
    "No number here is new; everything is copied from those files (lat/lng and the "
    "metro index are hand-mapped and say so). All shares are 0-1 fractions. "
    "Yash's fixtures/{region,site,company}.json and then the API replace this file."
)

KNOWN_CLUSTERS = {
    "PJM/DOM": "Northern Virginia",
    "PJM/AEP": "Central Ohio",
    "SWPP/OPPD": "Omaha",
    "ERCO/NCEN": "Dallas",
}

REGION_IDS = [
    "PJM/DOM", "PJM", "PJM/AEP", "AZPS", "SWPP/OPPD", "SWPP", "ERCO/NRTH",
    "ERCO/FWES", "ERCO/NCEN", "TEPC", "SC", "WACM", "NYIS",
]

SITE_REQUEST = {"mw": 300, "flat_24_7": True,
                "candidates": ["Phoenix, AZ", "Northern Virginia", "Omaha, NE"]}

# Hand-mapped metro -> region id. Coordinates are approximate metro centroids
# (degrees). serving_utility is the retail utility for the metro core; the
# region's operators list (scripts/operators_manual.json) is the authority
# where one exists.
METRO_INDEX = [
    ("Northern Virginia", "PJM/DOM", 39.04, -77.49, "Dominion Energy Virginia"),
    ("Richmond, VA", "PJM/DOM", 37.54, -77.44, "Dominion Energy Virginia"),
    ("Columbus, OH", "PJM/AEP", 39.96, -83.00, "AEP Ohio"),
    ("Chicago, IL", "PJM/CE", 41.88, -87.63, "ComEd (Exelon)"),
    ("Dallas, TX", "ERCO/NCEN", 32.78, -96.80, "Oncor Electric Delivery"),
    ("Midland/Odessa (Permian), TX", "ERCO/FWES", 31.99, -102.08, "Oncor Electric Delivery / TNMP"),
    ("Abilene, TX", "ERCO/NRTH", 32.45, -99.73, "AEP Texas North / Oncor"),
    ("San Antonio, TX", "ERCO/SCEN", 29.42, -98.49, "CPS Energy"),
    ("Austin, TX", "ERCO/SCEN", 30.27, -97.74, "Austin Energy"),
    ("Houston, TX", "ERCO/COAS", 29.76, -95.37, "CenterPoint Energy Houston Electric"),
    ("Omaha, NE", "SWPP/OPPD", 41.26, -95.94, "Omaha Public Power District"),
    ("Kansas City, MO", "SWPP/KCPL", 39.10, -94.58, "Evergy"),
    ("Phoenix, AZ", "AZPS", 33.45, -112.07, "Arizona Public Service"),
    ("Tucson, AZ", "TEPC", 32.22, -110.97, "Tucson Electric Power"),
    ("Las Vegas, NV", "NEVP", 36.17, -115.14, "NV Energy"),
    ("Salt Lake City, UT", "PACE", 40.76, -111.89, "Rocky Mountain Power (PacifiCorp)"),
    ("Denver, CO", "PSCO", 39.74, -104.99, "Xcel Energy Colorado"),
    ("Cheyenne, WY", "WACM", 41.14, -104.82, "Black Hills Energy (Cheyenne Light)"),
    ("Hillsboro, OR", "PGE", 45.52, -122.99, "Portland General Electric"),
    ("Prineville, OR", "PACW", 44.30, -120.83, "Pacific Power (PacifiCorp)"),
    ("Los Angeles, CA", "LDWP", 34.05, -118.24, "LADWP"),
    ("Santa Clara, CA", "CISO/PGAE", 37.35, -121.95, "Silicon Valley Power (inside PG&E TAC area)"),
    ("Minneapolis, MN", "MISO/0001", 44.98, -93.27, "Xcel Energy"),
    ("Des Moines / Altoona, IA", "MISO/0035", 41.59, -93.62, "MidAmerican Energy"),
    ("Atlanta, GA", "SOCO", 33.75, -84.39, "Georgia Power"),
    ("Newton County, GA", "SOCO", 33.55, -83.86, "Georgia Power / Walton EMC"),
    ("Nashville, TN", "TVA", 36.16, -86.78, "Nashville Electric Service (TVA)"),
    ("Gallatin, TN", "TVA", 36.39, -86.45, "Gallatin Dept. of Electricity (TVA)"),
    ("Memphis, TN", "TVA", 35.15, -90.05, "MLGW (TVA)"),
    ("Charlotte, NC", "DUK", 35.23, -80.84, "Duke Energy Carolinas"),
    ("Raleigh, NC", "CPLE", 35.78, -78.64, "Duke Energy Progress"),
    ("Berkeley County (Santee Cooper), SC", "SC", 33.19, -80.01, "Santee Cooper"),
    ("New York City, NY", "NYIS/ZONJ", 40.71, -74.01, "Con Edison"),
    ("Boston, MA", "ISNE/4008", 42.36, -71.06, "Eversource"),
]

# Coordinates for the mock company's sites (hand-mapped, approximate).
SITE_COORDS = {
    "Prineville, OR": (44.30, -120.83),
    "Altoona, IA": (41.64, -93.46),
    "Newton County, GA": (33.55, -83.86),
    "Gallatin, TN": (36.39, -86.45),
}


def load(rel):
    with open(os.path.join(REPO, rel)) as f:
        return json.load(f)


def dump(obj, name, **kw):
    path = os.path.join(HERE, name)
    with open(path, "w") as f:
        json.dump(obj, f, allow_nan=False, **kw)
    return path, os.path.getsize(path)


def header():
    return {"_provisional": True, "_generated": GENERATED, "_note": NOTE}


def yr(d, y):
    return (d or {}).get(str(y))


# --------------------------------------------------------------------------
def main():
    data = load("dashboard/public/data/regions.json")
    meta, regions = data["meta"], data["regions"]
    by_id = {r["id"]: r for r in regions}
    alerts_doc = load("dashboard/public/data/alerts.json")
    ops_manual = load("scripts/operators_manual.json")
    mock = load("claims/companies.mock.json")

    missing = [m[1] for m in METRO_INDEX if m[1] not in by_id]
    if missing:
        sys.exit(f"metro index maps to unknown region ids: {missing}")
    for rid in REGION_IDS:
        if rid not in by_id:
            sys.exit(f"unknown region id in REGION_IDS: {rid}")

    def parent_of(r):
        return by_id[r["ba"]] if r["type"] == "zone" else None

    def siting_of(r):
        # Zones inherit the parent BA's generation figures, so siting comes
        # from the parent (identical in regions.json, but be explicit).
        p = parent_of(r)
        src = p if p is not None else r
        return src["siting"], src["id"]

    # ---------------------------------------------------------------- opening
    pjm, dom = by_id["PJM"], by_id["PJM/DOM"]
    years = ("2019", "2025")

    def two(d, key=None):
        out = {}
        for y in years:
            v = yr(d, y)
            out[y] = (v.get(key) if (key and v is not None) else v)
        return out

    pjm_block = {
        "overnight_clean_mw": two(pjm["cf_avg_mw"], "overnight"),
        "overnight_total_mw": two(pjm["total_avg_mw"], "overnight"),
        "overnight_cf_share": two(pjm["cf_share"], "overnight"),
        "overnight_net_export_mw": {
            **two(pjm["interchange"], "overnight_net_export_mw"),
            "sign": "positive = export",
            "source": "EIA-adjusted operations table; partner-level table unreliable for PJM before 2020",
        },
        "fuel_delta_overnight_gw": pjm["fuel_delta_overnight_gw"],
        "dom_overnight_demand_mw": two(dom["demand"], "overnight_avg_mw"),
        "dom_avg_demand_mw": two(dom["demand"], "avg_mw"),
        "profile_24h": pjm.get("profile_24h"),
        "overnight_fuel_mw": pjm.get("overnight_fuel_mw"),
        "cf_share": pjm.get("cf_share"),
        "cf_avg_mw": pjm.get("cf_avg_mw"),
        "total_avg_mw": pjm.get("total_avg_mw")
    }

    flagged_ids = set(meta["data_flags"].keys())
    validation_ids = set(meta["detector"]["validation_named_in_advance"])
    scored = sorted((r for r in regions if r.get("detection")),
                    key=lambda r: r["detection"]["rank"])
    det_rows = []
    for r in scored:
        d = r["detection"]
        cf25 = yr(r["cf_share"], 2025)
        dm25 = yr(r["demand"], 2025)
        det_rows.append({
            "id": r["id"], "ba": r["ba"], "zone": r["zone"], "type": r["type"],
            "name": r["name"], "ba_name": r["ba_name"],
            "rank": d["rank"], "score": d["score"], "pattern": d["pattern"],
            "growth_pct": d["growth_pct"],
            "overnight_excess": d["overnight_excess"],
            "neighbor_divergence": d["neighbor_divergence"],
            "load_factor_delta": d["load_factor_delta"],
            "avg_mw_2025": dm25.get("avg_mw") if dm25 else None,
            "overnight_cf_share_2025": cf25.get("overnight") if cf25 else None,
            "data_flagged": r["id"] in flagged_ids,
            "validation": r["id"] in validation_ids,
            "known_cluster_label": KNOWN_CLUSTERS.get(r["id"]),
        })
    # Top-10 flat-load regions not named in advance and not data-flagged; a parent grid is not a
    # separate lead when one of its own zones already is (ERCOT when N. Texas leads).
    cand = [row for row in det_rows
            if row["rank"] <= 10 and row["id"] not in KNOWN_CLUSTERS
            and not row["data_flagged"] and row.get("pattern") == "flat-load growth"]
    ids = {row["id"] for row in cand}
    new_leads = [row["id"] for row in cand
                 if "/" in row["id"] or not any(x.startswith(row["id"] + "/") for x in ids)]

    opening = {
        **header(),
        "headline": meta["headline"],
        "data_snapshot_end": meta["data_snapshot_end"],
        "baseline_year": meta["baseline_year"],
        "overnight_hours_local": meta["overnight_hours_local"],
        "daytime_hours_local": meta["daytime_hours_local"],
        "pjm": pjm_block,
        "national": {"cf_share": meta["national"]["cf_share"],
                     "cf_avg_mw": meta["national"]["cf_avg_mw"]},
        "detector": {
            "n_scored": meta["detector"]["n_scored"],
            "method": meta["detector"]["method"],
            "validation_named_in_advance": meta["detector"]["validation_named_in_advance"],
            "known_clusters": KNOWN_CLUSTERS,
            "new_leads": new_leads,
            "regions": det_rows,
        },
        "caveats": meta["caveats"],
        "pattern_labels": meta["pattern_labels"],
        "data_flags": meta["data_flags"],
    }

    # ----------------------------------------------------------------- region
    heat_cache = {}

    def heatmap_for(r):
        uri = r["heatmap_uri"]
        if uri not in heat_cache:
            with open(os.path.join(PUB, uri)) as f:
                heat_cache[uri] = json.load(f)
        return heat_cache[uri]

    region_out = {}
    for rid in REGION_IDS:
        r = copy.deepcopy(by_id[rid])
        p = parent_of(r)
        r["parent"] = copy.deepcopy(p) if p is not None else None
        r["heatmap"] = copy.deepcopy(heatmap_for(by_id[rid]))
        r["operators_manual"] = ops_manual.get(rid, [])
        r["alerts"] = [a for a in alerts_doc["alerts"] if a.get("region") == rid]
        region_out[rid] = r
    region = {**header(),
              "alerts_meta": {"generated": alerts_doc["generated"],
                              "latest_month": alerts_doc["latest_month"],
                              "rules": alerts_doc["rules"],
                              "excluded_regions": alerts_doc["excluded_regions"]},
              "regions": region_out}

    # ------------------------------------------------------------------- site
    metro_rows = [{"metro": m, "region_id": rid, "ba": by_id[rid]["ba"],
                   "zone": by_id[rid]["zone"], "lat": lat, "lng": lng,
                   "serving_utility": su}
                  for (m, rid, lat, lng, su) in METRO_INDEX]
    metro_by_name = {m["metro"]: m for m in metro_rows}

    def largest_positive(fd):
        best = None
        for fuel, v in (fd or {}).items():
            if v is not None and v > 0 and (best is None or v > best[1]):
                best = (fuel, v)
        return {"fuel": best[0], "delta_gw": best[1]} if best else {"fuel": None, "delta_gw": None}

    results = []
    for cand in SITE_REQUEST["candidates"]:
        m = metro_by_name[cand]
        r = by_id[m["region_id"]]
        siting, siting_from = siting_of(r)
        ops = ops_manual.get(r["id"], [])
        d = r.get("detection") or {}
        results.append({
            "metro": cand, "region_id": r["id"], "ba": r["ba"], "zone": r["zone"],
            "cf_inherited_from_ba": r["cf_inherited_from_ba"],
            "serving_utility": ops[0]["utility"] if ops else m["serving_utility"],
            "operators": ops,
            "siting": siting,
            "siting_from": siting_from,
            "fuel_delta_overnight_gw": r["fuel_delta_overnight_gw"],
            "last_growth_filled_by": largest_positive(r["fuel_delta_overnight_gw"]),
            "overnight_fuel_mw_2025": yr(r["overnight_fuel_mw"], 2025),
            "detector": {"rank": d.get("rank"), "score": d.get("score"),
                         "pattern": d.get("pattern"), "growth_pct": d.get("growth_pct")},
            "demand": yr(r["demand"], 2025),
            "headroom_note": "no capacity headroom claimed; slope only",
            "lat": m["lat"], "lng": m["lng"],
        })
    results.sort(key=lambda x: -(x["siting"]["siting_score"] if x["siting"]["siting_score"] is not None else -1e9))
    for i, x in enumerate(results, 1):
        x["rank"] = i
    site = {**header(),
            "request": SITE_REQUEST,
            "metro_index": {"hand_mapped": True,
                            "note": "Hand-mapped metro -> region id; lat/lng are approximate metro centroids, not from the data.",
                            "metros": metro_rows},
            "ranking_key": "siting.siting_score (higher = cleaner); zones use the parent BA's siting",
            "results": results,
            "caveats": meta["caveats"]}

    # ---------------------------------------------------------------- company
    companies = {}
    for c in mock:
        c = copy.deepcopy(c)
        for s in c["sites"]:
            s["zone"] = s.get("pjm_zone")
            s["region_id"] = f'{s["ba"]}/{s["zone"]}' if s["zone"] else s["ba"]
            if s["region_id"] not in by_id:
                sys.exit(f"company site maps to unknown region id: {s['region_id']}")
            lat, lng = SITE_COORDS.get(s["metro"], (None, None))
            s["lat"], s["lng"] = lat, lng
        counts = {}
        for cl in c["claims"]:
            counts[cl["verdict"]] = counts.get(cl["verdict"], 0) + 1
            for e in cl.get("evidence", []):
                if e.get("type") == "grid":
                    reg = by_id.get(e["ba"])
                    cf = yr(reg["cf_share"], e["year"]) if reg else None
                    e["overnight_cf_share"] = cf.get("overnight") if cf else None
        c["verdict_counts"] = counts
        c["cannot_verify_count"] = counts.get("cannot_verify", 0)
        companies[c["ticker"]] = c
    company = {**header(), "companies": companies}

    # ------------------------------------------------------------------ write
    sizes = {}
    for name, obj in (("opening.json", opening), ("site.json", site), ("company.json", company)):
        sizes[name] = dump(obj, name, indent=1)
    path, n = dump(region, "region.json", indent=1)
    if n > 3_000_000:
        path, n = dump(region, "region.json", separators=(",", ":"))
    if n > 3_000_000:
        for r in region["regions"].values():
            r["heatmap"]["cf_share"] = [[None if v is None else round(v, 3) for v in row]
                                        for row in r["heatmap"]["cf_share"]]
        path, n = dump(region, "region.json", separators=(",", ":"))
    sizes["region.json"] = (path, n)

    for name, (path, n) in sizes.items():
        print(f"{name:14s} {n/1e6:6.2f} MB  {path}")
    print("new_leads:", new_leads)
    print("site ranking:", [(x["rank"], x["metro"], x["region_id"], x["siting"]["siting_score"]) for x in results])


if __name__ == "__main__":
    main()
